name: 'tomlcheck'
on:
  push:
    paths:
      - '**.toml'

jobs:
  tomlcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml
      - name: Check TOML syntax
        shell: python
        run: |
          import glob, re, sys, toml
          for file in glob.glob('**.toml'):
              try:
                  x = toml.load(file)
              except toml.decoder.TomlDecodeError:
                  e = str(sys.exc_info()[1])
                  mx = re.match('(.*) \(line (\d+) column (\d+) char (\d+)\)', e)
                  message, line, col, byte = mx.groups()
                  print(f'::error file={file},line={line},col={col}::{message}')
